# Generated by Django 3.0.8 on 2020-07-03 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blogger', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='Tags',
        ),
    ]
