# Generated by Django 3.0.8 on 2020-07-10 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blogger', '0002_auto_20200703_0112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='the_tag_posts',
        ),
        migrations.RemoveField(
            model_name='writer',
            name='user',
        ),
        migrations.DeleteModel(
            name='Posts',
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
        migrations.DeleteModel(
            name='Writer',
        ),
    ]
