# Generated by Django 3.0.8 on 2020-07-10 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogger', '0005_auto_20200710_0247'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
