# Generated by Django 3.0.8 on 2020-07-11 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogger', '0006_posts_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['date_created']},
        ),
        migrations.AddField(
            model_name='posts',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='date_edited',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
