# Generated by Django 3.0.8 on 2020-07-11 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blogger', '0007_auto_20200711_0000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['-date_created']},
        ),
        migrations.RemoveField(
            model_name='writer',
            name='pic_profile',
        ),
    ]
