# Generated by Django 3.0.8 on 2020-07-17 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blogger', '0008_auto_20200711_2255'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
