# Generated by Django 3.0.8 on 2020-07-18 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogger', '0010_posts_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='post_description',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
