# Generated by Django 3.0.8 on 2020-07-19 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogger', '0012_auto_20200718_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='post_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
