# Generated by Django 3.0.8 on 2020-07-19 00:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogger', '0013_posts_post_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='post_pic',
            field=models.ImageField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'png'])]),
        ),
    ]
